//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Necati_Meral_Yahoo_De.Logic.Ads.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Necati_Meral_Yahoo_De.Logic.Ads.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Output ähnelt.
        /// </summary>
        internal static string ReadAdsDataNodeData {
            get {
                return ResourceManager.GetString("ReadAdsDataNodeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data type ähnelt.
        /// </summary>
        internal static string ReadAdsDataNodeDataType {
            get {
                return ResourceManager.GetString("ReadAdsDataNodeDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diagnostic message ähnelt.
        /// </summary>
        internal static string ReadAdsDataNodeDiagnostics {
            get {
                return ResourceManager.GetString("ReadAdsDataNodeDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index-Group ähnelt.
        /// </summary>
        internal static string ReadAdsDataNodeIndexGroup {
            get {
                return ResourceManager.GetString("ReadAdsDataNodeIndexGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index-Offset ähnelt.
        /// </summary>
        internal static string ReadAdsDataNodeIndexOffset {
            get {
                return ResourceManager.GetString("ReadAdsDataNodeIndexOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NET ID ähnelt.
        /// </summary>
        internal static string ReadAdsDataNodeNetId {
            get {
                return ResourceManager.GetString("ReadAdsDataNodeNetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Port ähnelt.
        /// </summary>
        internal static string ReadAdsDataNodePort {
            get {
                return ResourceManager.GetString("ReadAdsDataNodePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remote-Address ähnelt.
        /// </summary>
        internal static string ReadAdsDataNodeRemoteAddress {
            get {
                return ResourceManager.GetString("ReadAdsDataNodeRemoteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trigger ähnelt.
        /// </summary>
        internal static string ReadAdsDataNodeTrgger {
            get {
                return ResourceManager.GetString("ReadAdsDataNodeTrgger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input ähnelt.
        /// </summary>
        internal static string WriteAdsDataNodeData {
            get {
                return ResourceManager.GetString("WriteAdsDataNodeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data type ähnelt.
        /// </summary>
        internal static string WriteAdsDataNodeDataType {
            get {
                return ResourceManager.GetString("WriteAdsDataNodeDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diagnostic message ähnelt.
        /// </summary>
        internal static string WriteAdsDataNodeDiagnostics {
            get {
                return ResourceManager.GetString("WriteAdsDataNodeDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index-Group ähnelt.
        /// </summary>
        internal static string WriteAdsDataNodeIndexGroup {
            get {
                return ResourceManager.GetString("WriteAdsDataNodeIndexGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Index-Offset ähnelt.
        /// </summary>
        internal static string WriteAdsDataNodeIndexOffset {
            get {
                return ResourceManager.GetString("WriteAdsDataNodeIndexOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NET ID ähnelt.
        /// </summary>
        internal static string WriteAdsDataNodeNetId {
            get {
                return ResourceManager.GetString("WriteAdsDataNodeNetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Port ähnelt.
        /// </summary>
        internal static string WriteAdsDataNodePort {
            get {
                return ResourceManager.GetString("WriteAdsDataNodePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remote-Address ähnelt.
        /// </summary>
        internal static string WriteAdsDataNodeRemoteAddress {
            get {
                return ResourceManager.GetString("WriteAdsDataNodeRemoteAddress", resourceCulture);
            }
        }
    }
}
