name: Release Logic Nodes

on:
  push:
    tags:
    - "v*.*.*"

jobs:
  logic-nodes:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.15
      with:
        useConfigFile: true

    # Set version
    - name: Set Version
      run: |
        .\build\set-version.ps1 -Version ${{ steps.gitversion.outputs.majorMinorPatch }}

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # Restore
    - name: Restore
      run: dotnet restore "dotnet"

    # Build the solution
    - name: Build
      run: dotnet build "dotnet" --no-restore -c Release

    # Execute all unit tests in the solution
    - name: Test
      run: dotnet test "dotnet" --no-build -c Release

    # Decode the base 64 encoded pfx and save the Signing_Certificate
    - name: Decode the pfx
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String($Env:GIRA_CERT_CONTENT)
        $certificatePath = Join-Path -Path "build" -ChildPath GitHubActionsWorkflow.pfx
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
      env:
        GIRA_CERT_CONTENT: ${{ secrets.GIRA_CERT_CONTENT }}

    # Set version
    - name: Sign packages
      run: |
        .\build\create-packages.ps1 -SigniningCertFile .\build\GitHubActionsWorkflow.pfx -SigniningCertPass $Env:GIRA_CERT_PASS
      env:
        GIRA_CERT_PASS: ${{ secrets.GIRA_CERT_PASS }}

    # Remove the pfx
    - name: Remove the pfx
      run: Remove-Item -path .\build\GitHubActionsWorkflow.pfx

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*.zip
        generate_release_notes: true

    # Upload the packages: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Logic nodes
        path: dist/*.zip
